-- Tests for the completion-pass surface: joint motors/limits, multibody joints, body locks/forces/
-- pose/mass reads, collider shape-swap/events/reads, narrow-phase contact + intersection queries,
-- filtered raycast, and world tuning. Loads the real shim via FFI — LuaJIT, from the repo root.
local rapier = require("rapier")

local function ball(w, x, y)
  local b = w:newBody("dynamic", x, y)
  w:attachCollider(b, "ball", 0.5)
  return b
end

describe("rapier.World completion surface", function()
  describe("joint motors + limits", function()
    it("clamps a revolute joint's angle with limits", function()
      local w = rapier.newWorld()
      local a = w:newBody("fixed", 0, 0)
      local b = w:newBody("dynamic", 1, 0)
      w:attachCollider(b, "cuboid", 0.5, 0.2)
      local j = w:revoluteJoint(a, b, 1, 0, 0, 0)
      w:setJointLimits(j, "ang", -0.2, 0.2)
      for _ = 1, 60 do
        w:applyTorqueImpulse(b, 5)
        w:step(1 / 60)
      end
      assert.is_true(math.abs(w:rotation(b)) < 0.4, "limit did not hold (angle=" .. w:rotation(b) .. ")")
    end)

    it("spins a body with a revolute motor", function()
      local w = rapier.newWorld()
      local a = w:newBody("fixed", 0, 0)
      local b = w:newBody("dynamic", 1, 0)
      w:attachCollider(b, "cuboid", 0.5, 0.2)
      local j = w:revoluteJoint(a, b, 1, 0, 0, 0)
      w:setJointMotorMaxForce(j, "ang", 1000)
      w:setJointMotor(j, "ang", 0, 8, 0, 5) -- target velocity 8
      for _ = 1, 180 do w:step(1 / 60) end
      assert.is_true(math.abs(w:angvel(b)) > 1, "motor produced no spin (angvel=" .. w:angvel(b) .. ")")
    end)
  end)

  describe("multibody joints", function()
    it("creates an articulated revolute joint that holds its anchor radius", function()
      local w = rapier.newWorld()
      w:setGravity(0, -10)
      local a = w:newBody("fixed", 0, 0)
      local b = w:newBody("dynamic", 1, 0)
      w:attachCollider(b, "ball", 0.3)
      local j = w:multibodyRevoluteJoint(a, b, 0, 0, -1, 0)
      assert.is_not_nil(j)
      for _ = 1, 120 do w:step(1 / 60) end
      local x, y = w:position(b)
      local r = math.sqrt(x * x + y * y)
      assert.is_true(r > 0.6 and r < 1.4, "articulated body left its orbit radius (r=" .. r .. ")")
      w:removeMultibodyJoint(j)
    end)
  end)

  describe("body locks / forces / pose / reads", function()
    it("locks translation so impulses don't move the body", function()
      local w = rapier.newWorld()
      local b = ball(w, 0, 0)
      w:lockTranslations(b, true)
      w:applyImpulse(b, 50, 50)
      for _ = 1, 30 do w:step(1 / 60) end
      local x, y = w:position(b)
      assert.is_true(math.abs(x) < 0.05 and math.abs(y) < 0.05, "locked body moved")
    end)

    it("forbids translation on a single axis", function()
      local w = rapier.newWorld()
      w:setGravity(0, -10)
      local b = ball(w, 0, 0)
      w:setEnabledTranslations(b, true, false) -- x free, y locked
      w:setLinvel(b, 5, 0) -- only x; gravity is the y force the lock must defeat
      for _ = 1, 30 do w:step(1 / 60) end
      local x, y = w:position(b)
      assert.is_true(math.abs(y) < 0.05, "y-locked body fell (y=" .. y .. ")")
      assert.is_true(x > 0.5, "x-free body didn't move")
    end)

    it("clears accumulated force with resetForces", function()
      local w = rapier.newWorld()
      local b = ball(w, 0, 0)
      w:addForce(b, 100, 0)
      w:resetForces(b)
      w:step(1 / 60)
      assert.is_true(math.abs(select(1, w:linvel(b))) < 0.01, "force was not cleared")
    end)

    it("sets a full pose and reads body type / enabled / center of mass", function()
      local w = rapier.newWorld()
      local b = ball(w, 0, 0)
      w:setPose(b, 3, 4, 0)
      local x, y = w:position(b)
      assert.is_true(math.abs(x - 3) < 0.01 and math.abs(y - 4) < 0.01)
      assert.equals("dynamic", w:bodyType(b))
      w:setBodyType(b, "fixed")
      assert.equals("fixed", w:bodyType(b))
      assert.is_true(w:isEnabled(b))
      w:setEnabled(b, false)
      assert.is_false(w:isEnabled(b))
      local cx, cy = w:centerOfMass(b)
      assert.is_true(math.abs(cx - 3) < 0.2 and math.abs(cy - 4) < 0.2)
    end)
  end)

  describe("collider shape swap + reads", function()
    it("swaps shape and reflects it in volume", function()
      local w = rapier.newWorld()
      local b = w:newBody("dynamic", 0, 0)
      local c = w:attachCollider(b, "ball", 1.0)
      local vBall = w:colliderVolume(c)
      assert.is_true(math.abs(vBall - math.pi) < 0.2, "ball area off (" .. vBall .. ")")
      w:setShape(c, "cuboid", 1.0, 1.0)
      assert.is_true(math.abs(w:colliderVolume(c) - 4) < 0.2, "cuboid area off after swap")
    end)

    it("reads density / mass / parent / sensor", function()
      local w = rapier.newWorld()
      local b = w:newBody("dynamic", 0, 0)
      local c = w:attachCollider(b, "ball", 0.5)
      assert.is_true(w:colliderDensity(c) > 0)
      assert.is_true(w:colliderMass(c) > 0)
      assert.is_not_nil(w:colliderParent(c))
      assert.is_false(w:colliderIsSensor(c))
      w:setSensor(c, true)
      assert.is_true(w:colliderIsSensor(c))
      assert.is_nil(w:colliderParent(w:staticCollider("ball", 9, 9, 0.5)), "static collider has no parent")
    end)

    it("silences events with setActiveEvents but still collides", function()
      local w = rapier.newWorld()
      local wallC = w:staticCollider("cuboid", 5, 0, 0.5, 5)
      w:setActiveEvents(wallC, false, false)
      -- An event fires if *either* collider in the pair has events, so silence both.
      local b = w:newBody("dynamic", 0, 0)
      local bc = w:attachCollider(b, "ball", 0.5)
      w:setActiveEvents(bc, false, false)
      w:setLinvel(b, 15, 0)
      local events = 0
      for _ = 1, 120 do
        w:step(1 / 60)
        events = events + #w:drainEvents()
      end
      assert.equals(0, events, "events were emitted despite being disabled")
      assert.is_true(w:position(b) < 5, "still should be blocked")
    end)
  end)

  describe("narrow-phase contact / intersection queries", function()
    it("lists colliders in solid contact", function()
      local w = rapier.newWorld()
      local wallC = w:staticCollider("cuboid", 5, 0, 0.5, 5)
      local b = w:newBody("dynamic", 4, 0)
      local bc = w:attachCollider(b, "ball", 0.5)
      for _ = 1, 40 do
        w:setLinvel(b, 5, 0) -- keep pressing into the wall
        w:step(1 / 60)
      end
      local contacts = w:contactsWith(bc)
      assert.is_true(#contacts >= 1, "no contacts reported while pressed against the wall")
      assert.equals(wallC, contacts[1])
    end)

    it("lists colliders intersecting a sensor", function()
      local w = rapier.newWorld()
      local sensor = w:staticCollider("cuboid", 0, 0, 2, 2)
      w:setSensor(sensor, true)
      local b = w:newBody("dynamic", 0, 0)
      local bc = w:attachCollider(b, "ball", 0.5)
      w:step(1 / 60)
      local hits = w:intersectionsWith(bc)
      assert.is_true(#hits >= 1, "sensor overlap not reported")
      assert.equals(sensor, hits[1])
    end)
  end)

  describe("filtered raycast", function()
    it("honors collision groups", function()
      local w = rapier.newWorld()
      local wallC = w:staticCollider("cuboid", 5, 0, 0.5, 5)
      w:setGroups(wallC, 0x0001, 0xFFFF)
      w:step(1 / 60)
      assert.is_not_nil(w:raycastFiltered(0, 0, 1, 0, 100, 0x0001, 0x0001),
        "matching-group ray should hit")
      assert.is_nil(w:raycastFiltered(0, 0, 1, 0, 100, 0x0002, 0x0002),
        "disjoint-group ray should miss")
    end)

    it("excludes a specific collider", function()
      local w = rapier.newWorld()
      local wallC = w:staticCollider("cuboid", 5, 0, 0.5, 5)
      w:step(1 / 60)
      assert.is_not_nil(w:raycastFiltered(0, 0, 1, 0, 100))
      assert.is_nil(w:raycastFiltered(0, 0, 1, 0, 100, 0xFFFF, 0xFFFF, wallC),
        "excluded collider should not be hit")
    end)
  end)

  describe("world tuning", function()
    it("accepts length unit + max ccd substeps without breaking the sim", function()
      local w = rapier.newWorld()
      w:setLengthUnit(1.0)
      w:setMaxCcdSubsteps(2)
      local b = ball(w, 0, 0)
      w:setLinvel(b, 3, 0)
      w:step(1 / 60)
      assert.is_true(w:position(b) > 0)
    end)
  end)
end)
