-- Tests for the extended World surface: world config, angular/extended body control, collider
-- materials/offsets, the extra static shapes, joints, the extended queries, and generalized KCC.
-- Loads the real shim via FFI — run under LuaJIT from the repo root.
local rapier = require("rapier")

local function wall(w, x)
  return w:staticCollider("cuboid", x, 0, 0.5, 5)
end

describe("rapier.World extended surface", function()
  describe("world config + gravity", function()
    it("applies world gravity to bodies that have mass", function()
      local w = rapier.newWorld()
      w:setGravity(0, -10)
      local b = w:newBody("dynamic", 0, 0)
      w:attachCollider(b, "ball", 0.5) -- gives the body mass
      for _ = 1, 60 do w:step(1 / 60) end
      local _, y = w:position(b)
      assert.is_true(y < -0.5, "body did not fall under gravity (y=" .. y .. ")")
    end)

    it("respects per-body gravity scale", function()
      local w = rapier.newWorld()
      w:setGravity(0, -10)
      local floaty = w:newBody("dynamic", 0, 0)
      w:attachCollider(floaty, "ball", 0.5)
      w:setGravityScale(floaty, 0)
      local heavy = w:newBody("dynamic", 5, 0)
      w:attachCollider(heavy, "ball", 0.5)
      for _ = 1, 60 do w:step(1 / 60) end
      assert.is_true(math.abs(select(2, w:position(floaty))) < 0.01, "gravity-scale 0 still fell")
      assert.is_true(select(2, w:position(heavy)) < -0.5, "gravity-scale 1 didn't fall")
    end)

    it("setSolverIterations does not error", function()
      local w = rapier.newWorld()
      w:setSolverIterations(8)
      local b = w:newBody("dynamic", 0, 0)
      w:setLinvel(b, 1, 0)
      w:step(1 / 60)
      assert.is_true(w:position(b) > 0)
    end)
  end)

  describe("angular + extended body control", function()
    it("spins under an angular impulse and reports angvel", function()
      local w = rapier.newWorld()
      local b = w:newBody("dynamic", 0, 0)
      w:attachCollider(b, "cuboid", 0.5, 0.5)
      w:applyTorqueImpulse(b, 2)
      w:step(1 / 60)
      assert.is_true(w:angvel(b) > 0.001, "no angular velocity from torque impulse")
      assert.is_true(math.abs(w:rotation(b)) > 0, "did not rotate")
    end)

    it("sets angular velocity directly", function()
      local w = rapier.newWorld()
      local b = w:newBody("dynamic", 0, 0)
      w:attachCollider(b, "cuboid", 0.5, 0.5)
      w:setAngvel(b, 3)
      assert.is_true(math.abs(w:angvel(b) - 3) < 0.01)
    end)

    it("changes body type at runtime (fixed ignores velocity)", function()
      local w = rapier.newWorld()
      local b = w:newBody("dynamic", 0, 0)
      w:setLinvel(b, 5, 0)
      w:setBodyType(b, "fixed")
      for _ = 1, 30 do w:step(1 / 60) end
      assert.is_true(math.abs(w:position(b)) < 0.01, "fixed body still moved")
    end)

    it("reports and augments mass", function()
      local w = rapier.newWorld()
      local b = w:newBody("dynamic", 0, 0)
      w:attachCollider(b, "ball", 0.5)
      local m0 = w:mass(b)
      assert.is_true(m0 > 0, "collider gave no mass")
      w:setAdditionalMass(b, 10)
      w:step(1 / 60) -- mass properties recompute on the next step
      assert.is_true(w:mass(b) > m0 + 9, "additional mass not applied")
    end)

    it("sleeps and wakes", function()
      local w = rapier.newWorld()
      local b = w:newBody("dynamic", 0, 0)
      w:attachCollider(b, "ball", 0.5)
      w:sleep(b)
      w:step(1 / 60)
      assert.is_true(w:isSleeping(b), "body did not stay asleep")
      w:applyImpulse(b, 5, 0)
      w:step(1 / 60)
      assert.is_false(w:isSleeping(b), "impulse did not wake the body")
    end)
  end)

  describe("collider materials + config + offsets", function()
    it("bounces more with higher restitution", function()
      local function maxUpwardVel(restitution)
        local w = rapier.newWorld()
        w:setGravity(0, -20)
        w:staticCollider("cuboid", 0, -3, 5, 0.5) -- floor
        local b = w:newBody("dynamic", 0, 0)
        local c = w:attachCollider(b, "ball", 0.5)
        w:setRestitution(c, restitution)
        local best = -1e9
        for _ = 1, 180 do
          w:step(1 / 60)
          best = math.max(best, (select(2, w:linvel(b))))
        end
        return best
      end
      assert.is_true(maxUpwardVel(0.9) > 1, "elastic ball never bounced upward")
      assert.is_true(maxUpwardVel(0.0) < 0.5, "inelastic ball bounced")
    end)

    it("disables a collider so it stops blocking", function()
      local w = rapier.newWorld()
      local c = wall(w, 5)
      w:setColliderEnabled(c, false)
      local b = w:newBody("dynamic", 0, 0)
      w:attachCollider(b, "ball", 0.5)
      w:setLinvel(b, 20, 0)
      for _ = 1, 120 do w:step(1 / 60) end
      assert.is_true(w:position(b) > 6, "disabled collider still blocked")
    end)

    it("offsets an attached collider from its parent body", function()
      local w = rapier.newWorld()
      local b = w:newBody("dynamic", 0, 0)
      local c = w:attachCollider(b, "ball", 0.5)
      w:setTranslationWrtParent(c, 1, 0)
      w:step(1 / 60)
      local px = w:colliderPosition(c)
      assert.is_true(math.abs(px - 1) < 0.05, "collider offset not reflected (px=" .. px .. ")")
    end)

    it("accepts friction/density/mass setters", function()
      local w = rapier.newWorld()
      local b = w:newBody("dynamic", 0, 0)
      local c = w:attachCollider(b, "ball", 0.5)
      w:setFriction(c, 0.8)
      w:setDensity(c, 2.0)
      w:setColliderMass(c, 3.0)
      w:setSolverGroups(c, 0x0001, 0xFFFF)
      w:step(1 / 60)
      assert.is_true(w:mass(b) > 0)
    end)
  end)

  describe("extended static shapes", function()
    it("creates triangle / segment / polyline / heightfield / hull colliders", function()
      local w = rapier.newWorld()
      assert.is_not_nil(w:staticTriangle(4.5, -1, 5.5, -1, 5, 1))
      assert.is_not_nil(w:staticSegment(0, 5, 10, 5))
      assert.is_not_nil(w:staticPolyline({ { 5, -5 }, { 5, 5 } }))
      assert.is_not_nil(w:staticHeightfield({ 0, 1, 0, 1 }, 4, 1))
      assert.is_not_nil(w:staticConvexHull({ { 0, 0 }, { 1, 0 }, { 1, 1 }, { 0, 1 } }))
    end)

    it("blocks a body against a polyline wall", function()
      local w = rapier.newWorld()
      w:staticPolyline({ { 5, -5 }, { 5, 5 } }) -- vertical wall at x=5
      local b = w:newBody("dynamic", 0, 0)
      w:attachCollider(b, "ball", 0.5)
      w:setLinvel(b, 8, 0)
      for _ = 1, 240 do w:step(1 / 60) end
      assert.is_true(w:position(b) < 5, "polyline wall did not block (x=" .. w:position(b) .. ")")
    end)
  end)

  describe("joints", function()
    it("caps distance with a rope joint and frees it on removal", function()
      local function fallDistance(removeIt)
        local w = rapier.newWorld()
        w:setGravity(0, -10)
        local anchor = w:newBody("fixed", 0, 0)
        local b = w:newBody("dynamic", 0, -1)
        w:attachCollider(b, "ball", 0.5)
        local j = w:ropeJoint(anchor, b, 2.0)
        if removeIt then w:removeJoint(j) end
        for _ = 1, 180 do w:step(1 / 60) end
        return -select(2, w:position(b)) -- how far below the anchor it ended up
      end
      assert.is_true(fallDistance(false) < 2.5, "rope did not cap the fall")
      assert.is_true(fallDistance(true) > 4, "removing the joint did not free the body")
    end)

    it("welds two bodies with a fixed joint", function()
      local w = rapier.newWorld()
      local anchor = w:newBody("fixed", 0, 0)
      local b = w:newBody("dynamic", 1, 0)
      w:attachCollider(b, "ball", 0.5)
      w:fixedJoint(anchor, b, 1, 0, 0, 0) -- hold B at A-local (1,0)
      w:applyImpulse(b, 0, 20)
      for _ = 1, 120 do w:step(1 / 60) end
      local x, y = w:position(b)
      local dist = math.sqrt((x - 1) ^ 2 + y ^ 2)
      assert.is_true(dist < 0.6, "fixed joint did not hold the body (drift=" .. dist .. ")")
    end)

    it("creates revolute / prismatic / spring joints without error", function()
      local w = rapier.newWorld()
      local a = w:newBody("fixed", 0, 0)
      local b = w:newBody("dynamic", 1, 0)
      w:attachCollider(b, "ball", 0.5)
      assert.is_not_nil(w:revoluteJoint(a, b, 0, 0, -1, 0))
      local c = w:newBody("dynamic", 0, 1)
      assert.is_not_nil(w:prismaticJoint(a, c, 0, 0, 0, 0, 1, 0))
      local d = w:newBody("dynamic", 0, 2)
      assert.is_not_nil(w:springJoint(a, d, 1.0, 100, 5, 0, 0, 0, 0))
      for _ = 1, 30 do w:step(1 / 60) end
      assert.is_true(true) -- stepping a jointed world doesn't crash
    end)
  end)

  describe("extended queries", function()
    it("raycasts and returns a surface normal", function()
      local w = rapier.newWorld()
      wall(w, 5)
      w:step(1 / 60)
      local c, toi, nx, ny = w:raycastNormal(0, 0, 1, 0, 100)
      assert.is_not_nil(c)
      assert.is_true(toi > 3 and toi < 6)
      assert.is_true(nx < -0.5, "left-face normal should point back toward the ray (nx=" .. nx .. ")")
      assert.is_true(math.abs(ny) < 0.5)
    end)

    it("sweeps a shape and reports time of impact", function()
      local w = rapier.newWorld()
      wall(w, 5)
      w:step(1 / 60)
      local c, toi = w:shapeCast("ball", 0.5, 0, 0, 0, 0, 1, 0, 100)
      assert.is_not_nil(c)
      assert.is_true(toi > 3 and toi < 5, "shapecast toi out of range: " .. tostring(toi))
    end)

    it("projects a point onto the nearest collider", function()
      local w = rapier.newWorld()
      wall(w, 5)
      w:step(1 / 60)
      local c, px, _, inside = w:projectPoint(0, 0, 100)
      assert.is_not_nil(c)
      assert.is_true(math.abs(px - 4.5) < 0.2, "nearest surface point off (px=" .. px .. ")")
      assert.is_false(inside)
      assert.is_true(select(4, w:projectPoint(5, 0, 100)), "point inside the wall should report inside")
    end)

    it("overlaps an arbitrary shape", function()
      local w = rapier.newWorld()
      wall(w, 5)
      w:step(1 / 60)
      assert.is_true(#w:overlapShape("cuboid", 1, 1, 5, 0, 0) >= 1)
      assert.equals(0, #w:overlapShape("ball", 1, 0, 50, 50, 0))
    end)
  end)

  describe("generalized kinematic character controller", function()
    it("clamps a box character's move against a wall and reports grounded", function()
      local w = rapier.newWorld()
      wall(w, 5)
      w:step(1 / 60)
      local dx, dy, grounded = w:moveShape("cuboid", 0.3, 0.3, 0, 0, 0, 10, 0, 0.01)
      assert.is_true(dx > 0 and dx < 9, "box KCC did not clamp into the wall (dx=" .. dx .. ")")
      assert.is_true(math.abs(dy) < 0.5)
      assert.is_boolean(grounded)
    end)
  end)
end)
