#ifndef RAPIER_SHIM_H
#define RAPIER_SHIM_H

/* Generated by cbindgen. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque physics world handle passed across the FFI boundary as `*mut PhysicsWorld`.
 */
typedef struct PhysicsWorld PhysicsWorld;

/**
 * One collision/sensor event, flattened for the C boundary.
 */
typedef struct {
  uint64_t a;
  uint64_t b;
  int32_t started;
  int32_t sensor;
} ContactRecord;

/**
 * Create a new physics world (top-down: zero gravity). Free with `shim_world_free`.
 */
PhysicsWorld *shim_world_new(void);

/**
 * Free a world created by `shim_world_new`.
 */
void shim_world_free(PhysicsWorld *world);

/**
 * Advance the simulation by `dt` seconds (caller drives the fixed timestep).
 */
void shim_world_step(PhysicsWorld *world, float dt);

/**
 * Number of collision/sensor events queued since the last `shim_events_clear`.
 */
uint32_t shim_events_count(PhysicsWorld *world);

/**
 * Copy event `i` into `out`. Returns 1 on success, 0 if out of range.
 */
int32_t shim_events_get(PhysicsWorld *world, uint32_t i, ContactRecord *out);

/**
 * Drop all queued events (call once per frame after draining).
 */
void shim_events_clear(PhysicsWorld *world);

/**
 * Create a rigid body of `kind` (0=dynamic, 1=fixed/static, 2=kinematic-velocity) at (x, y).
 */
uint64_t shim_body_create(PhysicsWorld *world, int32_t kind, float x, float y);

void shim_body_remove(PhysicsWorld *world, uint64_t handle);

void shim_body_position(PhysicsWorld *world, uint64_t handle, float *out_x, float *out_y);

/**
 * Body rotation angle (radians), for rendering orientation.
 */
float shim_body_rotation(PhysicsWorld *world, uint64_t handle);

/**
 * Teleport a body (no velocity change).
 */
void shim_body_set_translation(PhysicsWorld *world, uint64_t handle, float x, float y);

void shim_body_set_linvel(PhysicsWorld *world, uint64_t handle, float vx, float vy);

void shim_body_linvel(PhysicsWorld *world, uint64_t handle, float *out_x, float *out_y);

void shim_body_lock_rotations(PhysicsWorld *world, uint64_t handle, bool locked);

void shim_body_set_linear_damping(PhysicsWorld *world, uint64_t handle, float damping);

/**
 * Apply an instantaneous impulse — knockback, explosion shove.
 */
void shim_body_apply_impulse(PhysicsWorld *world, uint64_t handle, float x, float y);

/**
 * Add a force (applied over the next step) — sustained pushes/wind.
 */
void shim_body_add_force(PhysicsWorld *world, uint64_t handle, float x, float y);

/**
 * Enable continuous collision detection so fast bodies don't tunnel thin walls.
 */
void shim_body_enable_ccd(PhysicsWorld *world, uint64_t handle, bool enabled);

/**
 * Attach a collider (shape: 0=ball,1=cuboid,2=capsule) to a body. Collision events enabled.
 */
uint64_t shim_collider_attach(PhysicsWorld *world, uint64_t body, int32_t shape, float a, float b);

/**
 * Create a free-standing static collider at (x, y) — map walls/obstacles, no body.
 */
uint64_t shim_collider_static(PhysicsWorld *world,
                              int32_t shape,
                              float x,
                              float y,
                              float a,
                              float b);

void shim_collider_remove(PhysicsWorld *world, uint64_t handle);

/**
 * Make a collider a sensor (intersections reported, no physical response) or solid again.
 */
void shim_collider_set_sensor(PhysicsWorld *world, uint64_t handle, bool sensor);

/**
 * Collision filtering: `memberships` = the groups this collider belongs to; `filter` = the groups
 * it may interact with. Two colliders collide iff each is in the other's filter (bitwise).
 */
void shim_collider_set_groups(PhysicsWorld *world,
                              uint64_t handle,
                              uint32_t memberships,
                              uint32_t filter);

/**
 * Raycast from (ox,oy) along (dx,dy) up to `max_toi`. On hit writes the collider handle + distance
 * and returns 1; else returns 0.
 */
int32_t shim_query_raycast(PhysicsWorld *world,
                           float ox,
                           float oy,
                           float dx,
                           float dy,
                           float max_toi,
                           uint64_t *out_collider,
                           float *out_toi);

/**
 * First collider containing point (px,py), or 0 if none. Writes its handle to `out_collider`.
 */
int32_t shim_query_point(PhysicsWorld *world, float px, float py, uint64_t *out_collider);

/**
 * Overlap test: all colliders intersecting a circle at (x,y). Fills the world's scratch buffer
 * (read back with `shim_overlap_count` / `shim_overlap_get`) and returns the count. For AoE.
 */
uint32_t shim_query_overlap_circle(PhysicsWorld *world, float x, float y, float radius);

uint32_t shim_overlap_count(PhysicsWorld *world);

uint64_t shim_overlap_get(PhysicsWorld *world, uint32_t i);

/**
 * Compute a collision-corrected movement for a ball-shaped character at (x,y) wanting to move by
 * (dx,dy). Writes the allowed translation to out_x/out_y (the caller then teleports the body).
 */
void shim_kcc_move_ball(PhysicsWorld *world,
                        float x,
                        float y,
                        float radius,
                        float dx,
                        float dy,
                        float *out_x,
                        float *out_y);

#endif  /* RAPIER_SHIM_H */
